## Manipulation des constructeurs

### Constructeur de base : array()

In [1]:
# chargement de la librairie numpy
import numpy as np

In [4]:
# Création d'un ndarray en utilisant le constructur array
# on appelle le constructeur et on passe les nombres qu'on veut
# avoir dans le tableau
# ex : tableau à 1 dimension contenant les  nombres 1,2 et 3
A = np.array([1, 2, 3])

In [6]:
# la taille du tableau ==> 3 éléments sur l'unique dimension
A.shape

(3,)

In [5]:
# le nombre de dimension ==> 1 dimension
A.ndim

1

In [7]:
# size retourne le nombre d'éléments dans le tableau
A.size

3

### Autre constructeur : zeros()

In [10]:
# D'autres constructeurs permettent d'initialiser le tableau avec certains 
# nombres et certaines dimensions

# zeros() permet d'initialiser le tableau avec des zéros
# en précisant le shape sous forme de tuple
B = np.zeros((3,2))
B # ==> tableau rempli de 3 lignes, 2 colonnes et rempli de 0

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
# dimension
B.ndim

2

In [13]:
# la taille
B.shape

(3, 2)

### Autre constructeur : ones()

In [18]:
# ones() permet d'initialiser le tableau avec des '1'
C  = np.ones((3,4))
C # ==> tableau rempli de 3 lignes, 4 colonnes et rempli de 1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
# taille = le produit de lignes * colonnes
C.size

12

### Autre constructeur : full()

In [23]:
# ones() permet d'initialiser le tableau un certain nombre (ex=9)
D = np.full((2,3),9)
D # ==> tableau rempli de 2 lignes, 3 colonnes et rempli de 9

array([[9, 9, 9],
       [9, 9, 9]])

### np.random.randn : Remplir des tableaux avec des nombres aléatoires

In [28]:
E = np.random.randn(3,4)
E # ==> tableau rempli de 6 lignes, 4 colonnes et rempli de nombres
# aléatoires mais distribués selon la distrubition normale centrée en 0

array([[ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502]])

In [29]:
# pour fixer le générateur aléatoires pour qu'il nous produise toujours
# le même résultat, il faut utiliser seed
np.random.seed(0)
F = np.random.randn(3,4)
F # ==> toujours le même résultat quand on exécute

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351]])

In [30]:
# pour avoir un autre résultat, utiliser un autre nombre
np.random.seed(12098)
G = np.random.randn(3,4)
G

array([[ 1.78256215, -2.03893727, -0.30107465,  0.96174701],
       [-0.64036381,  0.57226939,  0.66479754, -1.34260023],
       [ 1.1791773 , -0.39441678, -0.16684518,  0.62484165]])

### Autre constructeur : eye()

In [31]:
# eye() permet de créér une matrice identité à N*N dimensions
H  = np.eye(4)
H # ==> tableau rempli de 4 lignes, 4 colonnes et rempli de 1 ou 0

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Constructeur : linspace()

In [33]:
# linspace() : permet de créer un tableau à 1 dimension 
# en précisant un point de début, un point de fin et une quantité 
# d'éléments qu'on veut avoir dans le tableau, répartie de façon égale 
# entre le point de début et le point de fin 
# ex : 20 points répartis entre 0 et 20
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

### Constructeur : arange()

In [34]:
# arange() : permet de créer un tableau à 1 dimension 
# en précisant un point de début, un point de fin et le pas qu'on désire 
# avoir entre chacun des éléments
# ex : pas de 1 entre 0 et 10
np.arange(0, 10, 1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
# ex : pas de 0.5 entre 0 et 10
np.arange(0, 10, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

## DATA TYPE des tableaux : dtype

In [37]:
# on construisant un tableau on peut choisir quel type de données
# on veut avoir dans le tableau : dtype
# int, float, le nombre de bytes qu'occupe la valeur dans notre mémoire
# int32 : nombre qui occupe 32 bits
#  plus le nombre de bytes est grand, plus la précision est grande
# mais le programme s'exécutera plus lentement

In [38]:
# on peut choisir le type dans les constructeur avec paramètre dtype
#  si on choisit float sur 64 bytes ==> précis mais programme lent
np.linspace(0, 10, 20, dtype=np.float64)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [39]:
#  si on choisit float sur 16 bytes ==> moins précis mais programme rapide
np.linspace(0, 10, 20, dtype=np.float16)

array([ 0.    ,  0.5264,  1.053 ,  1.579 ,  2.105 ,  2.63  ,  3.158 ,
        3.684 ,  4.21  ,  4.74  ,  5.26  ,  5.79  ,  6.316 ,  6.844 ,
        7.367 ,  7.895 ,  8.42  ,  8.945 ,  9.48  , 10.    ],
      dtype=float16)

## MANIPULATION des tableaux

In [40]:
# A = tableau d'exemples n°1
A = np.zeros((3,2))
print(A)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [42]:
# B = tableau d'exemples n°2
B = np.ones((3,2))
print(B)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


## Assembler les tableaux soit de façon verticale soit horizontale

## Assemblage HORIZONTAL : hstack()

In [45]:
#  hstack() : assemblage horizontal
C = np.hstack((A, B))

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [46]:
# dimension du tableau assemblé:  3 lignes et 4 colonnes
C.shape

(3, 4)

## Assemblage VERTICAL : vstack()

In [50]:
#  vstack() : assemblage vertical
D = np.vstack((A, B))
D

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [52]:
# dimension du tableau assemblé:  6 lignes et 2 colonnes
D.shape

(6, 2)

In [82]:
# ces méthodes peuvent être utile pour des régressions avec numpy, 
# ajout dans la matrice une colonne de biais : 
# hstack (matrice, colonne de biais)

## Méthode : concatenate - horizontal axis=1

In [59]:
#  hstack() : assemblage horizontal
C = np.hstack((A, B))
print('*** C *************************')
print(C)
# identique à :
E = np.concatenate((A, B), axis=1)
print('*** E *************************')
print(E)

*** C *************************
[[0. 0. 1. 1.]
 [0. 0. 1. 1.]
 [0. 0. 1. 1.]]
*** E *************************
[[0. 0. 1. 1.]
 [0. 0. 1. 1.]
 [0. 0. 1. 1.]]


## Méthode : concatenate - vertical axis=0

In [92]:
#  vstack() : assemblage vertical
I = np.vstack((A, B))
print('*** I *************************')
print(I)
# identique à :
J = np.concatenate((A, B), axis=0)
print('*** J *************************')
print(J)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 1

In [61]:
# concatenate plus utilisée car pratique pour des tableaux à 3 dim 
# ==> axis=2
# meilleure compréhension des axes dans numpy

## Méthode : reshape()

In [62]:
# reshape() : permet de redimensionner la forme d'un tableau pour lui
# donner une nouvelle forme
# attention : que si le nombre d'éléments de la forme initiale = celle de
# la nouvelle forme (size)

In [66]:
# ex : tableau D de dimension (6,2) avec 12 éléments
# on peut redimensionner le tableau en  dimension (4,3) car 4*3 = 12 éléments
D = np.vstack((A, B))
print('Tableau D : \n',D)
print('Dimension :', D.shape)
print('Nbre éléments (taille) :', D.size)

Tableau D : 
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Dimension : (6, 2)
Nbre éléments (taille) : 12


In [69]:
D = D.reshape((3,4))
print('Tableau D : \n',D)

Tableau D : 
 [[0. 0. 0. 0.]
 [0. 0. 1. 1.]
 [1. 1. 1. 1.]]


In [70]:
#  reshape() est très utilisée dans les codes data sciences
# très utile pour créer un tableau à 1 dimension et préciser 1
A = np.array([1, 2, 3])
A.shape # 1 n'est pas précisé

(3,)

In [71]:
A = A.reshape((A.shape[0],1))
A.shape # dimension 3, 1

(3, 1)

In [73]:
# très utile pour faire des sommes sur les tableaux, il faut le '1'

## Méthode : squeeze()

In [74]:
#  mais 1 pas utile pour créer des graphiques, traiter des photos,
# il ne faut pas le 1 ==> utiliser la méthode squeeze() pour l'enlever

In [77]:
A = A.squeeze()
A.shape # plus le 1 (3, )

(3,)

## Méthode : ravel()

In [79]:
# ravel() : permet d'aplatir un tableau à 1 seule dimension
print(D)
D.shape # tableau à 3 lignes et 1 dimension

[[0. 0. 0. 0.]
 [0. 0. 1. 1.]
 [1. 1. 1. 1.]]


(3, 4)

In [80]:
D.ravel() # tous les éléments sont affichés à la suite sur 1 dimension

array([0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.])

In [81]:
# utile dans certains cas de figure de machine learning

## Exercice

In [89]:
# Exo : reshape, random.randn concatenate
def initialisation(m, n):
    # m : nombre de lignes
    # n : nombre de colonnes
    # retourne une matrice aleatoire (m, n+1)
    # avec une colonne biais (remplie de 1 tout à droite)
    A = np.random.randn(m,n)
    print('--- A -------------------------',A)
    B = np.ones((m,1), dtype=int)
    print('--- B -------------------------', B)
    C = np.concatenate((A, B), axis = 1)
    print('--- C -------------------------', C)
    print('Dimension de C :',C.shape)
    return C

In [90]:
initialisation(3,4)

--- A ------------------------- [[-0.65075297  0.32412201  1.18695566  1.48371364]
 [ 2.04695946  1.37005187 -0.1818697  -0.58330892]
 [-0.01152795 -0.83440793  0.82916304  0.16639213]]
--- B ------------------------- [[1]
 [1]
 [1]]
--- C ------------------------- [[-0.65075297  0.32412201  1.18695566  1.48371364  1.        ]
 [ 2.04695946  1.37005187 -0.1818697  -0.58330892  1.        ]
 [-0.01152795 -0.83440793  0.82916304  0.16639213  1.        ]]
Dimension de C : (3, 5)


array([[-0.65075297,  0.32412201,  1.18695566,  1.48371364,  1.        ],
       [ 2.04695946,  1.37005187, -0.1818697 , -0.58330892,  1.        ],
       [-0.01152795, -0.83440793,  0.82916304,  0.16639213,  1.        ]])