## BROADCASTING

In [1]:
# charger librairie numpy
import numpy as np

In [5]:
# aléatoire ayant les mêmes données
np.random.seed(0)

# Création des 2 tableaux de travail de même dimension
A = np.random.randint(0, 10, [2, 3])
A

array([[5, 0, 3],
       [3, 7, 9]])

In [6]:
B = np.ones((2,3)) 
B

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
#  BROADCASTING : ajouter directement A à B
A + B

array([[ 6.,  1.,  4.],
       [ 4.,  8., 10.]])

In [8]:
#  si on peut étendre certaines dimensions d'un tableau

In [9]:
#  opération entre un tableau et un scalaire ==> ça fonctionne
# car le tableau à 1 dimension à été étendu pour tous les éléments
A + 2

array([[ 7,  2,  5],
       [ 5,  9, 11]])

In [12]:
C = np.ones((2, 1)) # tableau à 2 éléments
A + C # ça fonctionne car étend le tableau

array([[ 6.,  1.,  4.],
       [ 4.,  8., 10.]])

In [13]:
D = np.ones(3, 1)
A + D # ne fonctionne pas à cause des règles de broad casting

TypeError: Cannot interpret '1' as a data type

In [15]:
#  ex E(4,1) et F(1,3)? marche ou pas ==> OUI extension mutuelle de E et F
E = np.ones((4, 1))
F = np.ones((1, 3))
E + F

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [16]:
# se méfier du broadcasting si dimension incomplète (manque 1)

## CORRECTION EXERCICE VIDEO 12

In [17]:
# tableau de travail
import numpy as np
np.random.seed(0)
A = np.random.randint(0, 100, [10,5])
A

array([[44, 47, 64, 67, 67],
       [ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58],
       [65, 39, 87, 46, 88],
       [81, 37, 25, 77, 72],
       [ 9, 20, 80, 69, 79],
       [47, 64, 82, 99, 88],
       [49, 29, 19, 19, 14],
       [39, 32, 65,  9, 57],
       [32, 31, 74, 23, 35]])

In [18]:
D = (A - A.mean(axis=0)) / A.std(axis=0)
D

array([[-0.02206157,  0.        ,  0.13173823,  0.72539252,  0.10755798],
       [-1.56637126,  1.61579632, -1.48676006, -0.33034307,  0.96802178],
       [ 1.12513992,  1.84021247,  1.03508612, -1.14768676, -0.27965074],
       [ 0.90452425, -0.35906585,  0.99744662,  0.0102168 ,  1.01104497],
       [ 1.6104944 , -0.44883231, -1.33620208,  1.0659524 ,  0.32267393],
       [-1.56637126, -1.21184724,  0.73397016,  0.7935045 ,  0.62383626],
       [ 0.11030784,  0.76301493,  0.80924915,  1.81518411,  1.01104497],
       [ 0.1985541 , -0.80789816, -1.56203905, -0.90929485, -2.17267111],
       [-0.24267724, -0.67324847,  0.16937773, -1.24985473, -0.32267393],
       [-0.55153918, -0.7181317 ,  0.50813319, -0.77307091, -1.26918412]])

In [19]:
# toutes les moyennes de D sont proches de 0 : la moyenne de chaque colonne
# =0
D.mean(axis=0)

array([-2.22044605e-17, -4.44089210e-17,  0.00000000e+00, -1.22124533e-16,
       -4.44089210e-17])

In [20]:
#  l'écart type de chaque colonne est égal à 1
D.std(axis=0)

array([1., 1., 1., 1., 1.])

In [21]:
# chacune de nos colonnes suivent une distribution normale gaussienne
# absolument parfaite ==> ça facilite l'apprentissage statistique