## Les fonctions de base built-in Python

### Fonction : abs()

In [1]:
# fonction abs() - Valeur absloue
x = -3 
print(abs(x))

3


### Fonction : round()

In [2]:
# fonction : round()- Arrondir un nombre décimal
x = 3.1456
print(round(x))

3


### Fonction  sur les LISTES: 

In [3]:
liste_1 = [0, 23, 14, -19]

### Fonction : max()

In [4]:
# fonction max() : retourne la valeur maximum contenue dans la liste
max(liste_1)

23

### Fonction : min()

In [5]:
# fonction min() : retourne valeur minimum contenue dans la liste
min(liste_1)

-19

### Fonction : len()

In [6]:
# fonction len() : retourne la taille = le nombre d'éléments dans la liste
len(liste_1)

4

### Fonction : sum()

In [7]:
# fonction sum() : retourne somme de tous les éléments de la liste (si int)
sum(liste_1)

18

### Fonction : all()

In [8]:
# fonction all():retourne True quand tous les éléments de la liste sont True
liste_2 = [True, True, False]
all(liste_2)

False

### Fonction : any()

In [9]:
# fonction any() : retourne True quand tous les éléments de la liste sont True
any(liste_2)

True

In [10]:
# all() et any() peuvent être utilisées sur des int : 0=False et toutes 
# les autres valeurs que 0 sont True
all(liste_1)

False

## Fonctions de conversion de types

In [11]:
x = 10

### Fonction : type()

In [12]:
# fonction type() : retourne le type de la variable
type(x)

int

### Fonction : str()

In [13]:
# fonction str() : transforme int en str ==> entreguillemets
y = str(x)

In [14]:
type(y)

str

### Fonction : int()

In [15]:
# fonction str() : transforme str en int... si le str est un int
y='20'
print(type(int(y)))
print(y)

<class 'int'>
20


### Fonction : float()

In [16]:
# fonction float() : transforme int  entier en float décimale
x=11
print(type(float(x)))
print(x)

<class 'float'>
11


In [17]:
liste_1 = [0, 61, 63, 243]

### Fonction : tuple()

In [18]:
# fonction tuple() : transforme liste [] en tuple ()
tuple_1 = tuple(liste_1)

### Fonction : liste()

In [19]:
# fonction list() : 
# 1. transforme  tuple () en liste [] 
list(tuple_1)

[0, 61, 63, 243]

In [20]:
# fonction list() : 
# 2. transforme  les clés du dictionnaire {} en liste [] 
inventaire = {
    "bananes" : 5000,
    "pommes" : 2094,
    "poires" : 412809
}
list(inventaire.keys())

['bananes', 'pommes', 'poires']

### Fonction : bin()

In [21]:
# fonction bin() : transforme un int en binaire
bin(15) # 1111

'0b1111'

### Fonction : bytes()

In [22]:
# fonction bytes() : transforme un int en bytes
bytes(15)

b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'

### Fonction : hex()

In [23]:
# fonction hex() : transforme un int en hexadécimales
hex(15)  # f

'0xf'

### Fonction : oct()

In [24]:
# fonction hex() : transforme un int en octets
oct(15) # 17

'0o17'

### Fonction : input()

In [25]:
# fonction input() : permet à l'utilisateur de saisir du texte
# la fonction retourne la saisie de l'utilisateur en str
x = input()
print(x)

bonjour
bonjour


In [26]:
# on peut entrer un message pour l'utilisateur
x = int(input('Entrez un nombre : '))

Entrez un nombre : 15


In [27]:
type(x)

int

### Fonction : format()

In [28]:
# fonction format() : peret de personnaliser les chaines de caractères
x = 25
ville = 'Paris'

message = 'La température est de {} degrés celsius à {}'.format(x, ville)
print(message)
# ou
message_2 = f'La température est de {x} degrés celsius à {ville}'
print(message_2)

La température est de 25 degrés celsius à Paris
La température est de 25 degrés celsius à Paris


In [29]:
# format() est utilisée dans datascience, pour accéder 
# à des clés d'un dico dans une boucle for

# exemples

import numpy as np

parametres = {
    "W1" : np.random.randn(2,4),
    "b1" : np.zeros((2,1)),
    "W2" : np.random.randn(2,2),
    "b2" : np.zeros((2,1))
}

print('-- PARAMETRES ---------------------------------------------------')
print(parametres)

print('-- METHODE 1 ----------------------------------------------------')

for i in range(1,3):
    print("Couche :", i)
    print(parametres["W{}".format(i)])
    
# ou

print('-- METHODE 2 ----------------------------------------------------')

for i in range(1,3):
    print("Couche :", i)
    print(parametres["W"+str(i)])

    

-- PARAMETRES ---------------------------------------------------
{'W1': array([[ 1.253689  , -0.33327765, -1.93226397, -1.65287525],
       [-1.49084256, -1.24660473, -0.32210011, -1.47888776]]), 'b1': array([[0.],
       [0.]]), 'W2': array([[ 0.06698128, -1.62850581],
       [ 0.0990599 ,  0.66443481]]), 'b2': array([[0.],
       [0.]])}
-- METHODE 1 ----------------------------------------------------
Couche : 1
[[ 1.253689   -0.33327765 -1.93226397 -1.65287525]
 [-1.49084256 -1.24660473 -0.32210011 -1.47888776]]
Couche : 2
[[ 0.06698128 -1.62850581]
 [ 0.0990599   0.66443481]]
-- METHODE 2 ----------------------------------------------------
Couche : 1
[[ 1.253689   -0.33327765 -1.93226397 -1.65287525]
 [-1.49084256 -1.24660473 -0.32210011 -1.47888776]]
Couche : 2
[[ 0.06698128 -1.62850581]
 [ 0.0990599   0.66443481]]


### Fonction : open()

In [30]:
# fonction open() : permet d'ouvrir des fichiers, de créer des fichiers
# et de les enregistrer sur l'ordinateur
# on doit passer en paramètres un fichier, un mode w : écriture
f =open('fichier.txt','w')

In [31]:
# Ecrire dans le fichier
f.write("bonjour")

7

In [32]:
#  une fois l'action terminée sur le fichier ==> close
f.close()

In [33]:
# dans le répertoire de travail, un fichier 'ficier.txt" a été créé
# si on l'ouvre, il contient 'bonjour'

In [34]:
# Pour lire le fichier : open en mode r (read)
f = open('fichier.txt','r')
print(f.read())
f.close()

bonjour


In [36]:
# dans la pratique, on utilise plutôt
# on fait ce que l'on veut dans ce fichier...
# pas la peine de fermer le fichier, python le fait
with open('fichier.txt','r') as f:
    print(f.read())

bonjour


In [ ]:
# Ecrire un algo qui écrit dans un fichier text tous les nombres
# carrés de 0 à 10 

In [38]:
with open('fichier.txt','w') as f:
    for i in range(10):
        f.write("{}^2 = {} \n".format(i, i**2))

In [64]:
# Exercice : lire le fichier.txt 
# et retourner une liste [0^2=0,1^2=2...,92=81]
with open('fichier.txt','r') as f:
    lignes=  f.readlines()
    for i in range(len(lignes)):
        lignes[i]= lignes[i].strip()
    print(lignes)

['0^2 = 0', '1^2 = 1', '2^2 = 4', '3^2 = 9', '4^2 = 16', '5^2 = 25', '6^2 = 36', '7^2 = 49', '8^2 = 64', '9^2 = 81']


In [66]:
# correction exercice de 0 à 20
carres_pairs = {
    str(k) : k**2 for k in range(0,20)
}
print(carres_pairs)

{'0': 0, '1': 1, '2': 4, '3': 9, '4': 16, '5': 25, '6': 36, '7': 49, '8': 64, '9': 81, '10': 100, '11': 121, '12': 144, '13': 169, '14': 196, '15': 225, '16': 256, '17': 289, '18': 324, '19': 361}
