## MATRICE - NUMPY

In [1]:
import numpy as np

In [4]:
A = np.array([[1, 2],[3, 4],[5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

## DIMENSION D'UNE MATRICE

In [5]:
A.shape
# matrice de dimension 3*2 ==> 3 lignes, 2 colonnes

(3, 2)

## TRANSPOSEE D'UNE MATRICE

In [6]:
# Transposée de A
A.T

array([[1, 3, 5],
       [2, 4, 6]])

In [7]:
A.T.shape
# matrice de dimension 2*3 ==> 2 lignes, 3 colonnes

(2, 3)

## ADDITION - SOUSTRACTION DE MATRICE

In [9]:
# Matrice remplie de 1
B=np.ones((3, 2))
B

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
# ADDITION
A+B

array([[2., 3.],
       [4., 5.],
       [6., 7.]])

## PRODUIT MATRICIEL

In [11]:
A.shape

(3, 2)

In [12]:
C=B.T

In [13]:
C.shape

(2, 3)

### produit matriciel : .dot()

In [14]:
A.dot(B.T)

array([[ 3.,  3.,  3.],
       [ 7.,  7.,  7.],
       [11., 11., 11.]])